language: node_js
node_js:
  - 'node'
  - '6'

deploy:
  provider: npm
  email: popodidi@livemail.tw
  apikey:
    secure: oiundsXR67qOZQQl7cXSX/QhEqIeLgthgEuVfG7vJLxYImdSCfPQwSnBcCjALskR/XAuUT6esZUrbV+mYutqRbgluDBfAaD8rmyWltPi1mT2mxq35uL6VDaMJnGV+vgOo+wkV6ABEIinqZv/4eGAfW8TCR+1+0bJBudqO77Bsm6fgQcuMt+JWhEoiltmFv4l80q1zUlJbbyc4N9Ig1ydTCikvJ9cmYcWJxzMMXdfSQioN4BBKUvjNzQdRwQIqvP9WJSoN7qPVjh4x3VEi9w2iOzXISQC51nQiQV7FeAqJpRbK3U6F+p78ZGStSBZSZi0cZFfHzlrwHVOXyu3wSZFl/iWlWrZCOT7IQw24CG5Evjsw0tjS1oZ90zVb3PxZiUt4+dfopu6OAvO++LRqf0rTURSi9m6rKZVpCdOZ+j1c/AvVRVnbX/Nyy7iVOSAEhkccxhDeX0obFLWWzfbuA7UToiaZHu/3ga2lUs50+7wMcs4PY2V4ilMywxTMylUrzQ67c7vybw9Tu5IXLR778RqlCjyEheVYCptMWkolswlON/UFtc1MIs1HV3i8IinqQ3fRKvmt8DyNBC2rJ9ykqgsRFeWIFZjkAK06kGbnfSTqg+lhVrjriDt1z4Q4Cb4ZA4jRKXAu7B/v75bJGlyhJdMh0lv+epsjCFeCn1HWVlpBHw=
  on:
    branch: master
    tags: true
    repo: popodidi/bookshelf-plugin-mode