before_install:
- npm install -g npm
- npm --version
language: node_js
node_js:
- node
- '6'
deploy:
  provider: npm
  skip_cleanup: true
  email: popodidi@livemail.tw
  apikey:
    secure: IMTd4FDN+107EhhzRUKmbWsHf/b/CPamDBYkapOu7xNJv7n+f+21Ehp0OF3kz3WdubN5Rv9a3c5TzAsDvOLuKzeu07BvC9pj16LSK2G62x//+TXYh99i6EP0IatfXDygOXBNGYgAdhOuvgQ6KWksNjNNVKVCZ7pLEUTxd7dOzICKwoTUcqsMzrfZ+d1t2ikwdRElCQXeB+wirrKrl9TuQkOEHHyIKWzOYM0dBr7+OIIgJ9pYzAUxN7oYJFHgQhxYV/H2IW6AcoGMyS96s4BMrc1EJEbCDPuIb2yd0qFdzi3UxssMkGTz0Yrdl+B1JQcupgVETz4oe3MQXg8CXnuOz8vC8whcMRDw5dcOkDijGM6/NYwmLqw9SgEORn8ohUn97KgvitzVeTHSnfuJob6qFX6BSR1PSVQsVM8l9wUlECyjp4SLFs1pomcQcMMktNiQ/0qve5f15QQ/M5GOl5rE8P8+ifLx5nSiXPIXNpXg6f3i/IxD+o5NHtGz04dU2dVVwPmXK103qXNz46g8kW+8x+mLWRlnD6LdL0u0tNo8O8/ZtiAlKAIlNuDu3fqTJ2NZRlJiN0BZa9K4XM3+eK5siZ4X1nzLiIHhVWVMVTH5RiCjTUkW8/A0FVsyajWS25bftZUBMKGokfCdw6RSFvzjFqV1nCBex/3m1Egk2NOVTkg=
  on:
    branch: master
    tags: true
    repo: popodidi/bookshelf-plugin-mode
