language: node_js
node_js:
- node
- '6'
deploy:
  provider: npm
  email: popodidi@livemail.tw
  apikey:
    secure: Xc1ZWnvIS52vOOLM4Ppb/HUiyCphCL24V50jnlC0u0gttD/LfdHBaR7B0Vz8xX3fVXYmWsSTBVFDXhhXdDJPGHpAdPoBDTg1jt8sHslGNeut9KHsE7Pee+KKHQOvndwROWRH9/jwC93cUrnTYPLhcQVMRTheIpTaQtbrDdTL9kLt79HdJ3ZiBTaIGdp7Zxe5QMcooTqoP21B7voipku7uilmhbYztukbYKLxxdWqJh6mhrcJJU2jGSXqQUxUQCmFTAIYRwp3K/VWPbpfatdYXZiLK14KkvLUqJepruX/hVvhIHEnPB6Pm6NMyYvfq8dTUuMsaA1aHgbuCF7IbRB6nlxSAS0dO1l28wO8BjbpFW7eBW2n5/CGDCH0A1uKkLI/7aevuCbK3N7tNMNmj6IU53HvfGB9zQt19PyHUdYPyJ4gbm2e4TOrpiaHpyb03d0lp7vsZLztE1MRCUHy2oUMVc0ZVrXwqUe0yL1CFlf7J3Pmnz5lyT2/5PP8K01BjvTlTgwr8pdR5qNTuJxFa63uaoKDohYE+wUTj9+39rNiQN2hNbcYhWla4s1Pqk5qKK7opQAbiVqomyVfxLnh19sM0IbaXq+KB/RZxLDZo95JWrTocnB3UPm+8ex0iQhTgKEO62zG5pjK5KLCDonHbHtP/144n/AUwWvfpJxTDcw0mA8=
  on:
    branch: master
    tags: true
    repo: popodidi/bookshelf-plugin-mode
