before_install:
  - npm install -g npm
  - npm --version

language: node_js
node_js:
- node
- '6'

deploy:
  provider: npm
  email: popodidi@livemail.tw
  apikey:
    secure: HTcZaD0yRs+RDPx4nBIkurBqYaIE08pcvYCe9/uS7fr8jge9dGmvbhhGp/U0r8+BxYD8aIc/PtmQMcU3WdVbCRAwAX5Cl3BmQ0wFb6C1emz42P64nuD9l3l60j/1jTgLHXtoyQ5iKcgq+37QuWAYnaW3GstWtGdkrvHNtKDpdiR4cA7lYn/hvxgveMmsBBKC1mN1WA6dSowQKbXARZDvGASqzN6fPnGohMai2i34CzT3DSwJ5D0rwB+9J47fmS2c0jOVi4+Faw+tbIpSWTng4KwhueqM2BIxJOPwxNN/kKt4dvBM37yDdY4SuJlgD17Ta+D2w/RAh7/uQ2+R7MYNAt8ALhttIMapSKYpjvYfS0ZRelBvj7a6QAoiaQxhYqW2HK07qex5oDMm9blrtTG2V0uYMGllb07NjEiOL4t3URQf7gxrFoZI3LWAuf4o8GouaOSyPZpzn4/NlCY/Pk1kYB/baDdsEG72QzeBfoUgdqc7SjTI5bURp3/UClPXMMm0cvugznYtLR/IQiUzmyQ9l0BXFsDFtTwU1FNQ8CTTB1Uaz5M7G4tB5vzKFunIA0KviFejYbm9pEadtOzWCBZw03s9zDurN5oDKmlEB6oFI8lbBNwjaiEf25t/hsbr3MGcH9Wa7iZQXJgj6p++e5WfXgVGbiWFzjenW22heSn3OzA=
  on:
    branch: master
    tags: true
    repo: popodidi/bookshelf-plugin-mode
env:
  global:
    secure: q9/GfoGHf1ZoD6gvmUqxzjRmM3RSuB4JznwPo5urkPIXHWp2swf3L9PE+m1fu/1Iicvkk3pQQQQLXaTXFC1dhdUlTgKhcEAX+bGyznxPHKFDIe18Asg+4dhHTc//tTui9p3RbcNUD6h5MDBTT9Tx8G6bNo1w4xjZGmG3ae7tv4hWM/Auci7lsSTeuACpWTsbfUOQOLj/UetKdTvpMRCjskYLZZM3GvqnA6Udk8CblT4gKViH/0XgCBSG0thmJQnBoqM/N54n5IOs+lunAQOgVAxcM4OfJFJtV1Mh6bbYBUngpaq2zNCU6S97U2YiwoOhf7YFd6RWACCQf+kcDK6tdvq33YkoY+LbKFOpdAvqWg/EY6+TYYv7O0PhrMZHn+hVP8Hhp61SiE4pKpD6uE8xuZaXkVZOskttnEjnSus5t4mZlrB8Np8EtImAyTuGGgpFrb+KwSqg5vxJM38Hok666mqnehT0ez9UJXc0XKSv+smbWfL70bybHkDw1PeiQ44sheT8vGNVEMg32HkOkh27CTiclBIxngQmx/zYmf1DGreIBmSY72JpsCNH1YMzpEpnI0FU7yUebz4lZEc0uje8lldLXVweSOOwTILE7JlNlFmdW/hteie072I9RQ44wwmxqzm7aICkPBvhcVy7d8TjX+zhph2NWeNQOY5IhEFMahM=
