language: node_js
node_js:
- node
- '6'
deploy:
  provider: npm
  email: popodidi@livemail.tw
  apikey:
    secure: HTcZaD0yRs+RDPx4nBIkurBqYaIE08pcvYCe9/uS7fr8jge9dGmvbhhGp/U0r8+BxYD8aIc/PtmQMcU3WdVbCRAwAX5Cl3BmQ0wFb6C1emz42P64nuD9l3l60j/1jTgLHXtoyQ5iKcgq+37QuWAYnaW3GstWtGdkrvHNtKDpdiR4cA7lYn/hvxgveMmsBBKC1mN1WA6dSowQKbXARZDvGASqzN6fPnGohMai2i34CzT3DSwJ5D0rwB+9J47fmS2c0jOVi4+Faw+tbIpSWTng4KwhueqM2BIxJOPwxNN/kKt4dvBM37yDdY4SuJlgD17Ta+D2w/RAh7/uQ2+R7MYNAt8ALhttIMapSKYpjvYfS0ZRelBvj7a6QAoiaQxhYqW2HK07qex5oDMm9blrtTG2V0uYMGllb07NjEiOL4t3URQf7gxrFoZI3LWAuf4o8GouaOSyPZpzn4/NlCY/Pk1kYB/baDdsEG72QzeBfoUgdqc7SjTI5bURp3/UClPXMMm0cvugznYtLR/IQiUzmyQ9l0BXFsDFtTwU1FNQ8CTTB1Uaz5M7G4tB5vzKFunIA0KviFejYbm9pEadtOzWCBZw03s9zDurN5oDKmlEB6oFI8lbBNwjaiEf25t/hsbr3MGcH9Wa7iZQXJgj6p++e5WfXgVGbiWFzjenW22heSn3OzA=
  on:
    branch: master
    tags: true
    repo: popodidi/bookshelf-plugin-mode
